### ISSUE TITLE
Issues with 'certificate signature failure'

### ISSUE THREAD

**Issue by agibsonIL** [rickert-lab/Italo#2]
https://github.com/rickert-lab/Italo/blob/3405fec75080f6709945b88a5abf698c3b10ead7/queries.py#L40

The issues that I'm seeing looks to be related to ssl.

I know this was deprecated since Python version 3.10 but the only fix that I have is to use the following:

```python
ssl=ssl.SSLContext(ssl.PROTOCOL_TLS)
```

I'm still investigating and will keep you update.

/cc @christianrickert

**Comment by christianrickert** [comment]
Here's what I see when I run the original code with two additional print statements (I) and the adjusted code (II):

Code I:
```Python
''' Italo.pyw'''
async def get_session(self, secrets_file="secrets.json"):
    """Read GraphQL credentials from a JSON-formatted text file and
    return an authenticated client session with the server.
    """
    session_client = None
    if os.path.isfile(secrets_file):
        secrets = queries.get_secrets(os.path.abspath(secrets_file))
    else:
        self.set_text(self.pentry, "Secrets missing: Template file created.", True)
        self.write_secrets(file=secrets_file)
        if platform.system() == "Windows":  # no support for macOS or Linux
            os.startfile(secrets_file)
        secrets = None
    try:
        credentials = await queries.get_credentials(secrets)
        print(f"Credentials: {credentials}")
    except aiohttp.client_exceptions.InvalidURL:
        self.set_text(self.pentry, "GraphQL server failed to respond.", True)
    except aiohttp.client_exceptions.ClientConnectionError:
        self.set_text(self.pentry, "GraphQL server failed to connect.", True)
    except aiohttp.client_exceptions.ClientResponseError:
        self.set_text(self.pentry, "GraphQL server reported 'bad request'.", True)
    else:  # success
        session_client = await queries.get_client(secrets, credentials)
        print(f"Session Client: {session_client}")
    finally:  # failure
        if not session_client:
            self.set_progress_bar()
        return session_client

''' queries.py'''
﻿﻿# create a session client for authorized requests
async def get_client(secrets, credentials):
    # configure client transport
    websocket_transport = gql_WebsocketsTransport(
        url=f"wss://{secrets['server_name']}/graphql",
        headers={"authorization": f"bearer {credentials['access_token']}"},
        ssl=ssl.create_default_context(),  # 👀
        keep_alive_timeout=300,
    )
    # configure session client with transport
    session_client = gql.Client(
        transport=websocket_transport, fetch_schema_from_transport=True
    )
    return session_client
```
Exception I:
```Terminal
Credentials: {'access_token': '[long token, removed]', 'expires_in': 3600, 'token_type': 'Bearer', 'scope': 'graphql serviceuser'}
Session Client: <gql.client.Client object at 0x000002013E88C620>
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<MainWindow.search_images() done, defined at C:\Users\HIMSR Staff\Desktop\Chris\Italo\v0.11\Italo.pyw:178> exception=ConnectionClosedError(None, Close(code=<CloseCode.MESSAGE_TOO_BIG: 1009>, reason=''), None)>
Traceback (most recent call last):
  File "C:\Software\venv\Italo\Lib\site-packages\websockets\legacy\protocol.py", line 953, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\websockets\legacy\protocol.py", line 1078, in read_message
    frame = await self.read_data_frame(max_size=max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\websockets\legacy\protocol.py", line 1098, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\websockets\legacy\protocol.py", line 1155, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\websockets\legacy\framing.py", line 95, in read
    raise PayloadTooBig(f"over size limit ({length} > {max_size} bytes)")
websockets.exceptions.PayloadTooBig: over size limit (4096 > 0 bytes)

Traceback (most recent call last):
  File "C:\Users\HIMSR Staff\Desktop\Chris\Italo\v0.11\Italo.pyw", line 186, in search_images
    async with session_client as client_session:
  File "C:\Software\venv\Italo\Lib\site-packages\gql\client.py", line 814, in __aenter__
    return await self.connect_async()

           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\gql\client.py", line 795, in connect_async
    await self.session.fetch_schema()
  File "C:\Software\venv\Italo\Lib\site-packages\gql\client.py", line 1661, in fetch_schema
    execution_result = await self.transport.execute(parse(introspection_query))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\gql\transport\websockets_base.py", line 432, in execute
    async for result in generator:
  File "C:\Software\venv\Italo\Lib\site-packages\gql\transport\websockets_base.py", line 388, in subscribe
    answer_type, execution_result = await listener.get()
                                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\gql\transport\websockets_base.py", line 56, in get
    raise item
  File "C:\Software\venv\Italo\Lib\site-packages\gql\transport\websockets_base.py", line 301, in _receive_data_loop
    answer = await self._receive()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\gql\transport\websockets_base.py", line 231, in _receive
    data: Data = await self.websocket.recv()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\websockets\legacy\protocol.py", line 562, in recv
    await self.ensure_open()
  File "C:\Software\venv\Italo\Lib\site-packages\websockets\legacy\protocol.py", line 938, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1009 (message too big); no close frame received
```

Code II:
```Python
﻿﻿'''queries.py'''
﻿# create a session client for authorized requests
async def get_client(secrets, credentials):
    # configure client transport
    websocket_transport = gql_WebsocketsTransport(
        url=f"wss://{secrets['server_name']}/graphql",
        headers={"authorization": f"bearer {credentials['access_token']}"},
        ssl=ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT),  # 👀
        keep_alive_timeout=300,
    )
    # configure session client with transport
    session_client = gql.Client(
        transport=websocket_transport, fetch_schema_from_transport=True
    )
    return session_client
```
Exception II:
```Terminal
Credentials: {'access_token': '[long token, removed]', 'expires_in': 3600, 'token_type': 'Bearer', 'scope': 'graphql serviceuser'}
Session Client: <gql.client.Client object at 0x000001EE3288A6C0>
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<MainWindow.search_images() done, defined at C:\Users\HIMSR Staff\Desktop\Chris\Italo\v0.11\Italo.pyw:178> exception=SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')>
Traceback (most recent call last):
  File "C:\Users\HIMSR Staff\Desktop\Chris\Italo\v0.11\Italo.pyw", line 186, in search_images
    async with session_client as client_session:
  File "C:\Software\venv\Italo\Lib\site-packages\gql\client.py", line 814, in __aenter__
    return await self.connect_async()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\gql\client.py", line 789, in connect_async
    await self.transport.connect()
  File "C:\Software\venv\Italo\Lib\site-packages\gql\transport\websockets_base.py", line 490, in connect
    self.websocket = await asyncio.wait_for(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\websockets\legacy\client.py", line 654, in __await_impl__
    _transport, protocol = await self._create_connection()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 1148, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 1181, in _create_connection_transport
    await waiter
  File "C:\Program Files\Python312\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "C:\Program Files\Python312\Lib\asyncio\sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files\Python312\Lib\ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
```
These two exceptions indicate different issues - I don't know if there's a common denominator.

**Comment by agibsonIL** [comment]
@christianrickert  maybe the ssl/tls issue is just an issue on my machine. For your `Code I` exception, it looks like you're hitting your max payload limit. To fix this you can add this argument `connect_args={"max_size": 5*(2**20)}` to your gql WebsocketsTransport.

new `get_client` method:
```python
# create a session client for authorized requests
async def get_client(secrets, credentials):
    # configure client transport
    websocket_transport = gql_WebsocketsTransport(
        url=f"wss://{secrets['server_name']}/graphql",
        headers={"authorization": f"bearer {credentials['access_token']}"},
        ssl=ssl.create_default_context(),
        connect_args={"max_size": 5*(2**20)}, # 👀
        keep_alive_timeout=300,
    )
    # configure session client with transport
    session_client = gql.Client(
        transport=websocket_transport, fetch_schema_from_transport=True
    )
    return session_client
``` 

Let me know if this works.

**Comment by christianrickert** [comment]
Setting the `max_size` parameter with `ssl.create_default_context()` for the [websockets protocol](https://gql.readthedocs.io/en/latest/transports/websockets.html#underlying-websockets-protocol) is a good workaround.
Is it possible that the HALO 3.6 GraphQL server set a default frame size limit, where HALO 4.0 GraphQL does not? Alternatively, is the server currently defaulting to a value of 0 bytes unless otherwise specified by the client?

Two more observations:

1.) When I switch to `﻿ssl.PROTOCOL_TLS_CLIENT`, see Indica Lab's [example code](https://gitlab.com/indica_labs_public/example-code/-/blame/main/examples/api/client.py?ref_type=heads#L20), I run into a certificate error.
```
Credentials: {'access_token': '[long token, removed]', 'expires_in': 3600, 'token_type': 'Bearer', 'scope': 'graphql serviceuser'}
Session Client: <gql.client.Client object at 0x000001E526671B50>
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<MainWindow.search_images() done, defined at C:\Users\HIMSR Staff\Desktop\Chris\Italo\v0.11\Italo.pyw:178> exception=SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')>
Traceback (most recent call last):
  File "C:\Users\HIMSR Staff\Desktop\Chris\Italo\v0.11\Italo.pyw", line 186, in search_images
    async with session_client as client_session:
  File "C:\Software\venv\Italo\Lib\site-packages\gql\client.py", line 814, in __aenter__
    return await self.connect_async()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\gql\client.py", line 789, in connect_async
    await self.transport.connect()
  File "C:\Software\venv\Italo\Lib\site-packages\gql\transport\websockets_base.py", line 490, in connect
    self.websocket = await asyncio.wait_for(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Software\venv\Italo\Lib\site-packages\websockets\legacy\client.py", line 654, in __await_impl__
    _transport, protocol = await self._create_connection()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 1148, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 1181, in _create_connection_transport
    await waiter
  File "C:\Program Files\Python312\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "C:\Program Files\Python312\Lib\asyncio\sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files\Python312\Lib\ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
```

2.) When I manually set the subprotocol to `[WebsocketsTransport.APOLLO_SUBPROTOCOL]`, see Indica Lab's [example code](https://gitlab.com/indica_labs_public/example-code/-/blame/main/examples/api/client.py?ref_type=heads#L19), I run into another error:
```Terminal
Credentials: {'access_token': '[long token, removed]', 'expires_in': 3600, 'token_type': 'Bearer', 'scope': 'graphql serviceuser'}
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<MainWindow.search_images() done, defined at C:\Users\HIMSR Staff\Desktop\Chris\Italo\v0.11\Italo.pyw:178> exception=TypeError("'NoneType' object does not support the asynchronous context manager protocol")>
Traceback (most recent call last):
  File "C:\Users\HIMSR Staff\Desktop\Chris\Italo\v0.11\Italo.pyw", line 186, in search_images
    async with session_client as client_session:
TypeError: 'NoneType' object does not support the asynchronous context manager protocol
```

However, the current workaround is sufficient to continue using my tool.

Thank you very much for your help! - I'll update my code to accomedate the new situation with HALO 4.0.
